#!/bin/sh

if [ "$#" -ne 1 ]; then
    echo "Usage: $0 BPL_FILE" >&2
    exit 1
fi
if ! [ -e $1 ]; then
    echo "$1 not found!" >&2
    exit 1
fi

BASENAME=`echo $1 | sed 's/\.[^\.]*$//'`
ASSEMBLY="$BASENAME.s"
python -m bpl $1
gcc $ASSEMBLY -o $BASENAME
